package payment

const (
	PAYMENT_CALLBACK_SUCCESS         string = "PAYMENT_CALLBACK_SUCCESS"         // FE
	PAYMENT_CALLBACK_CANCEL          string = "PAYMENT_CALLBACK_CANCEL"          // FE
	PAYMENT_CALLBACK_SUCCESS_PROCESS string = "PAYMENT_CALLBACK_SUCCESS_PROCESS" // Server
	PAYMENT_CALLBACK_CANCEL_PROCESS  string = "PAYMENT_CALLBACK_CANCEL_PROCESS"  // Server
)
